name: misa_app
description: "MISA - Mobile Invoice & Service Application untuk UMKM Jasa"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Auth
  google_sign_in: ^6.2.2

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # PDF
  pdf: ^3.11.3
  printing: ^5.13.4

  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  equatable: ^2.0.7
  path: ^1.8.0

  # Charts
  fl_chart: ^0.70.2

  # URL Launcher (untuk buka WhatsApp reminder)
  url_launcher: ^6.3.1

  # Local notifications
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
